MENU, MINHAS_FICHAS, CONSULTA_CONTEINER, CONSULTA_EMPRESA, SCAN, FOTOS, \
SELECIONA_FICHA, CONSULTA_FICHA, SELECIONA_RVF, CONSULTA_RVF, RVF_ABERTA, \
ADICIONA_DESCRICAO, ADICIONA_FOTO, TASEDA = range(14)
